spring.application.name=treino-abc-backend
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/treino_abc
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.org.springframework.security=DEBUG
logging.level.com.treino_abc_backend.security=DEBUG


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=Z3VhcmRhLXNlZ3VyYS1jaGF2ZS1wYXJhLUpXVF9zZWNyZXRv
jwt.expiration=86400000

spring.http.encoding.enabled=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.force=true


#spring.security.user.name=admin
#spring.security.user.password=1234
#spring.security.user.roles=ADMIN
