spring.application.name=treino-abc-backend
server.port=8080

spring.datasource.url=jdbc:postgresql://dpg-d3om0uh5pdvs73a0mbfg-a.oregon-postgres.render.com:5432/treino_abc
spring.datasource.username=treino_abc_user
spring.datasource.password=1RWaL9pKnpnxDBqsHFp6oodwIoeB7uZT
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Evitar timezone erro
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jackson.time-zone=America/Sao_Paulo


jwt.secret=Z3VhcmRhLXNlZ3VyYS1jaGF2ZS1wYXJhLUpXVF9zZWNyZXRv
jwt.expiration=86400000

spring.http.encoding.enabled=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.force=true


#spring.security.user.name=admin
#spring.security.user.password=1234
#spring.security.user.roles=ADMIN

